secure_input_notification: false
matches:
  - trigger: ":ssig "
    replace: |
      - - -

      Vesa V채nsk채
      +358 50 3079234
      Kisko Labs

      https://twitter.com/vesan
      https://www.kiskolabs.com
      https://www.wodconnect.com
  - trigger: ":ssiw "
    replace: |
      - - -

      Vesa V채nsk채
      WODconnect

      https://www.wodconnect.com
