---
language: python

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

before_install: 
  - docker pull mitermayer/vim-test-bed
  - yarn install

script: 
  - make lint test
